<h3>Menu <a href="#" class="menu-toggle">&times;</a></h3>
                    <br/>
                    <ul>
                        <li><a href="#">Home </a></li>
                        <li><a href="about.html">About </a></li>
                        <li><a href="outline.html">Course Outlines</a></li>
                        <!--Lessons SubMenu -->
                        <li><a href="#" onclick="$('#submenu').toggle();">Lessons</a></li>
                        <div id="submenu" style="display:none;">
                            <a href="week1.html" class="sub" target="_blank">Week1</a>
                            <a href="week2.html" class="sub" target="_blank">Week2</a>
                            <a href="week3.shtml" class="sub" target="_blank">Week3</a>
                            <a href="week4.html" class="sub" target="_blank">Week4</a>
                            <a href="week5.html" class="sub" target="_blank">Week5</a>
                        </div>
                        <!-- -->
                    </ul>